# Change these first
owner: hinterland-software # Your GitHub username
repo: uptime # Your GitHub repository name
assignees:
  - jroehl

# Add your sites here
sites:
  - name: hansekai-apartments
    url: http://hansekai-apartments.netlify.app
  - name: wakenitzmauer-luebeck
    url: https://wakenitzmauer-luebeck.de
  - name: carlaemrich
    url: https://carlaemrich.de
  - name: agenturgoeschen
    url: https://agenturgoeschen.com
  - name: strassburg-passage
    url: https://strassburg-passage.de
  - name: ivm-meyer
    url: https://ivm-meyer.de
  - name: bruecke-oh
    url: https://bruecke-oh.de
  - name: heidpartner
    url: https://heidpartner.de
  - name: vh-gruppe
    url: https://vh-gruppe.de
  - name: five-minutes
    url: https://five-minutes.app
  - name: hinterland-software
    url: https://hinterland.software
  - name: linkedin-portfolio
    url: https://johannroehl.de
  - name: cv-gen
    url: https://cv.johannroehl.de
  - name: contentful-gatsby-boilerplate
    url: http://contentful-gatsby-boilerplate.netlify.app

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://hinterland.software/images/HINTERLAND-software-bw.png
  name: Uptime monitor
  introTitle: '**Uptime monitor**'
  introMessage: Periodically checking pages created and run by [HINTERLAND software](https://hinterland.software/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: HINTERLAND software
      href: https://hinterland.software/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
